version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./service/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/artifact.tar.gz
    - build/appspec.yml
